kured:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 96Mi
  configuration:
    annotateNodes: true
    rebootSentinelCommand: sh -c "! needs-restarting --reboothint"
    timeZone: Asia/Dubai
