---
machine:
  network:
    hostname: metal3
    interfaces:
      - interface: eth0
        addresses:
          - 192.168.0.14/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.0.1
